### ISSUE TITLE
Broken URL

### ISSUE THREAD

**Issue by robmarkcole** [ludeeus/addon-sqlite-web#1]
# Problem/Motivation
The link https://github.com/hassio-addons/addon-sqlite-web/tree/master/README.md is broken

![image](https://user-images.githubusercontent.com/11855322/45010676-9e7bb580-b006-11e8-99e5-239909c8c4b6.png)

**Comment by ludeeus** [comment]
Since this repo only are intended as a temp storage before I can include it in the community org I will not change this.
